---
date: "4/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", fig.width = 8, fig.height=5, echo = FALSE, message=FALSE, warning=FALSE)
```

```{r run code}
library(readr)
library(tidyverse)
library(readxl)
library(zoo)
library(ggthemes)
library(extrafont)
library(kableExtra)

loadfonts(device = "win")

color_set <- c("#009639", "#FF9933", "#0033A0", "#b22234", "#FFCC00")



pop_lookup <- read_rds(here::here("population_lookup.rds"))

WesternEurope <- c("France",
            "Germany",
            "Italy",
            "Portugal",
            "Spain",
            "Belgium",
            "United Kingdom"
            )

pop_ofUSE <- data.frame(WesternEurope) %>%  
  rename(Combined_Key = WesternEurope) %>% 
  left_join(pop_lookup, by = "Combined_Key") %>%  
  summarize(Population_Count = sum(Population_Count)) %>%  
  pull()

# load data set downloaded from Data world
cc <- read_csv("data_world_download/COVID-19 Activity.csv",
col_types = cols(REPORT_DATE = col_date(format = "%Y-%m-%d"),
COUNTY_NAME = col_character(), COUNTY_FIPS_NUMBER = col_character(),
PEOPLE_POSITIVE_CASES_COUNT = col_number(),
PEOPLE_POSITIVE_NEW_CASES_COUNT = col_number(),
PEOPLE_DEATH_COUNT = col_number(),
PEOPLE_DEATH_NEW_COUNT = col_number()))   %>%
  select(Date = REPORT_DATE,
         Admin2 = COUNTY_NAME,
         Province_State = PROVINCE_STATE_NAME,
         Country_Region = COUNTRY_SHORT_NAME,
         country_code = COUNTRY_ALPHA_2_CODE,
         CONTINENT_NAME,
         Cases = PEOPLE_POSITIVE_CASES_COUNT,
         Difference = PEOPLE_POSITIVE_NEW_CASES_COUNT,
         Deaths = PEOPLE_DEATH_NEW_COUNT,
         Cumulative_Deaths = PEOPLE_DEATH_COUNT,
         ) %>%
  mutate(Combined_Key = paste(Admin2, Province_State, country_code, sep = ", ")) %>%
  left_join(pop_lookup, by = "Combined_Key") %>%
  mutate(infection_Rate = (Cases/Population_Count)*100000)

# cc <- read_csv("data_world_download/COVID-19 Activity.csv",
# col_types = cols(report_date = col_date(format = "%m/%d/%Y"),
# county_name = col_character(),
# county_fips_number = col_character(),
# people_positive_cases_count = col_number(),
# people_positive_new_cases_count = col_number(),
# people_death_count = col_number(),
# people_death_new_count = col_number()))   %>% 
#   select(Date = report_date,
#          Admin2 = county_name,
#          Province_State = province_state_name,
#          Country_Region = country_short_name,
#          country_code = country_alpha_2_code,
#          continent_name,
#          Cases = people_positive_cases_count,
#          Difference = people_positive_new_cases_count,
#          Deaths = people_death_new_count,
#          Cumulative_Deaths = people_death_count,
#          ) %>%
#   mutate(Combined_Key = paste(Admin2, Province_State, country_code, sep = ", ")) %>%
#   left_join(pop_lookup, by = "Combined_Key") %>%
#   mutate(infection_Rate = (Cases/Population_Count)*100000)
         






date_of_data <-  max(cc$Date) 
date_of_data <- format(date_of_data, "%d %B %Y")
subtitle <- paste("Data updated on ", date_of_data, sep = "") 
tspan <- 210

table1 <- cc %>%
  filter(Country_Region %in% WesternEurope | Country_Region == "United States" | Country_Region == "Russia" | Country_Region == "Brazil" | Country_Region == "India") %>%
  filter(Date >= max(as.Date(Date)) - tspan) %>%
  select(Country_Region, Date, Cases, Difference, Deaths, Cumulative_Deaths) %>%
  mutate(Group = ifelse(Country_Region %in% WesternEurope,
                        "WesternEurope", 
                        Country_Region
                        )) %>%
  group_by(Group, Date) %>%
  summarise_at(vars(Cases:Cumulative_Deaths), sum, na.rm = TRUE) %>%
  arrange(Group, desc(Date)) %>%
  mutate(percentage_change = (Cases - lead(Cases)) / lead(Cases)) %>%
  mutate(
    daily_new_cases_difference =
      Difference - lead(Difference)
  ) %>%
  filter(!is.na(percentage_change))

#create tables
p_change <- table1 %>%  
  ggplot(aes(x = Date, y = percentage_change, colour = Group)) +  
  geom_line() + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic() + 
  scale_colour_manual(values = color_set)

p_new_cases_difference <- table1 %>%  
  ggplot(aes(x = Date, y = daily_new_cases_difference)) +  
  geom_point(aes(x = Date, y = daily_new_cases_difference, colour = Group)) + 
  geom_segment(aes(x = Date, xend = Date, y = 0, yend = daily_new_cases_difference)) +
  geom_smooth() +
  facet_wrap(~ Group, nrow = 2) +
  theme_classic() + 
  scale_colour_manual(values = color_set)

p1 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Group, Date, Cases, Difference) %>%  
  ggplot(aes(x = Date, y = Cases, colour = Group)) +  
  geom_line() + 
  theme_classic() +
  labs(title = "Cumulative Cases") + 
  scale_colour_manual(values = color_set)

p2 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Group, Date, Cases, Difference) %>%  
  ggplot(aes(x = Date, y = Difference, colour = Group)) +  
  geom_point() +
  geom_segment(aes( x = Date, xend = Date, y = 0, yend = Difference), alpha = .5) +
  theme_classic() +
  scale_colour_manual(values = color_set) +
  geom_smooth(se = FALSE) + 
  facet_wrap(~Group) +
  labs(title = "Daily Cases")

p3 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Group, Date, Cumulative_Deaths) %>%  
  ggplot(aes(x = Date, y = Cumulative_Deaths, colour = Group)) +  
  theme_classic() +
  geom_line() + 
  labs(title = "Cumulative Deaths")+ 
  scale_colour_manual(values = color_set)

p4 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Group, Date, Deaths) %>%  
  ggplot(aes(x = Date, y = Deaths, colour = Group)) +  
  geom_point() +
  geom_segment(aes( x = Date, xend = Date, y = 0, yend = Deaths), alpha = .5) +
  theme_classic() +
  geom_smooth(se = FALSE)+ 
  facet_wrap(~Group) +
  labs(title = "Daily Deaths")+ 
  scale_colour_manual(values = color_set)




p5 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Group, Date, Cases, Difference) %>%  
  ggplot(aes(x = Date, y = Cases, colour = Group)) +  
  geom_line() + 
 scale_y_log10(
   breaks = scales::trans_breaks("log10", function(x) 10^x),
   labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  theme_classic() +
  annotation_logticks() +
  labs(title = "Cumulative Cases", subtitle = "Log Scale") + 
  scale_colour_manual(values = color_set)



p6 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Group, Date, Cumulative_Deaths) %>%  
  ggplot(aes(x = Date, y = Cumulative_Deaths, colour = Group)) +  
 scale_y_log10(
   breaks = scales::trans_breaks("log10", function(x) 10^x),
   labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  theme_classic() +
  annotation_logticks() +
  geom_line() + 
  labs(title = "Cumulative Deaths", subtitle = "Log Scale")+ 
  scale_colour_manual(values = color_set)
```

Comparision with Group of EU countries. Total population of selected EU countries (in millions) = `r pop_ofUSE`; population of USA is 325 million 

```{r countries}

  data.frame(WesternEurope) %>%  
  rename(Combined_Key = WesternEurope) %>% 
  left_join(pop_lookup, by = "Combined_Key") %>%  
  select(-Lat, -Long) %>% 
  mutate(Population_Count = scales::comma(Population_Count)) %>% 
  kable()  %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

```


```{r run charts}
library(patchwork)
p2 
p4

p1 + p3 
p5 + p6 

```







# Simple Recovery Calculation
```{r  recovered }
recovered <- table1 %>%  
  arrange(Group, Date) %>% 
  mutate(current = (Cases - lag(Cases, 45))/1000000) %>% 
  mutate(recovered = (lag(Cases, 45) - Cumulative_Deaths )/1000000)

p_recovered <- recovered %>%  
  ggplot() +
  geom_area(aes(x = Date,  y = recovered), fill = "green", colour = "black", alpha = .50) +
  geom_col(aes(x = Date, y = current, fill = Group), alpha = .50) +
  facet_wrap(~ Group) +
  theme_clean() +
  scale_fill_manual(values = color_set) +
  theme(legend.position = "none",
        panel.border = element_blank(),
        axis.line = element_blank()) + 
  labs(title = "Simple Recovery Trajectories", 
       subtitle = "In Millions",
       caption = "Assumption that infection lasts 45 days and all infected that survive are recovered")



p_recovered

p_change
p_new_cases_difference

```

































