---
title: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", fig.height = 3.85, fig.width = 7.5, echo = FALSE, message=FALSE, warning=FALSE)
# knitr::opts_chunk$set(fig.align = "center", fig.width = 8, fig.height=5, echo = FALSE, message=FALSE, warning=FALSE)
```

```{r run code}
library(readr)
library(tidyverse)
library(readxl)
library(zoo)
library(ggthemes)
library(extrafont)
library(pander)


loadfonts(device = "win")
pop_lookup <- read_rds(here::here("population_lookup.rds"))
tspan <-  60 
fdate <- Sys.Date() - tspan
font_family1 = "Book Antiqua"
font_color = "#011140"


#position of legend. 
legend_position = c("2020-05-15", 3000)


#load data set downloaded from Data world
cc <- read_csv("data_world_download/COVID-19 Activity.csv",
col_types = cols(REPORT_DATE = col_date(format ="%Y-%m-%d"),
COUNTY_NAME = col_character(), COUNTY_FIPS_NUMBER = col_character(),
PEOPLE_POSITIVE_CASES_COUNT = col_number(),
PEOPLE_POSITIVE_NEW_CASES_COUNT = col_number(),
PEOPLE_DEATH_COUNT = col_number(),
PEOPLE_DEATH_NEW_COUNT = col_number()))   %>% 
  select(Date = REPORT_DATE,
         Admin2 = COUNTY_NAME,
         Province_State = PROVINCE_STATE_NAME,
         Country_Region = COUNTRY_SHORT_NAME,
         country_code = COUNTRY_ALPHA_2_CODE,
         CONTINENT_NAME,
         Cases = PEOPLE_POSITIVE_CASES_COUNT,
         Difference = PEOPLE_POSITIVE_NEW_CASES_COUNT,
         Deaths = PEOPLE_DEATH_NEW_COUNT,
         Cumulative_Deaths = PEOPLE_DEATH_COUNT,
         ) %>%
  filter(country_code == "US") %>% 
  mutate(Combined_Key = paste(Admin2, Province_State, country_code, sep = ", ")) %>%  
  left_join(pop_lookup, by = "Combined_Key") %>% 
  mutate(infection_Rate = (Cases/Population_Count)*100000) 



date_of_data <-  max(cc$Date) 
date_of_data <- format(date_of_data, "%d %B %Y")
subtitle <- paste("Data updated on ", date_of_data, sep = "") 
tspan <- 120

Key <-  "Greenville, South Carolina, US"
State_Key <- "South Carolina"

#crunch data for report
table1 <- cc %>% 
  filter(Combined_Key == Key) %>% 
  select(Date, Cases, Difference, Deaths, Cumulative_Deaths) %>%  
  mutate(Date = as.Date(Date)) %>% arrange(desc(Date)) %>%  
  mutate(percentage_change = (Cases - lead(Cases))/lead(Cases)) %>% 
  mutate(daily_new_cases_difference = 
           Difference - lead(Difference)) %>%  
  filter(!is.na(percentage_change))



p1_high <-  cc %>% 
  filter(Combined_Key == Key) %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%
  summarize(cases_max = max(Cases)) %>% 
  pull()

p1 <- cc %>% 
  filter(Combined_Key == Key) %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Date, Cases, Difference) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Cases)) +  
  geom_line() + 
  scale_y_continuous(labels = scales::comma, breaks = seq(0, p1_high, 1000)) +
  theme_bw() +
  theme(text=element_text(family=font_family1, color = font_color)) +
  labs(title = "Cumulative Cases", 
       subtitle = "Greenville County", 
       caption = "Source:New York Times") + 
  ylab("Cumulative Cases")


p2_high <-  cc %>% 
  filter(Combined_Key == Key) %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Date, Cases, Difference) %>% 
  summarize(difference_high = max(Difference)) %>%  
  pull()


p2 <- cc %>% 
  filter(Combined_Key == Key) %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Date, Cases, Difference) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Difference)) + 
  scale_y_continuous(labels = scales::comma, breaks = seq(0, p2_high, 50)) +
  geom_point(size = 1) +
  geom_segment(aes( x = Date, xend = Date, y = 0, yend = Difference)) +
  theme_bw() +
  theme(text=element_text(family=font_family1, color = font_color)) +
  geom_smooth(se = FALSE)+ 
  labs(title = "Daily Cases", 
       subtitle = "Greenville County", 
       caption = "Source:New York Times") + 
  ylab("Daily Cases")

p3 <- cc %>% 
  filter(Combined_Key == Key) %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Date, Cumulative_Deaths) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Cumulative_Deaths)) +  
  theme_bw() +
  theme(text=element_text(family=font_family1, color = font_color)) +
  geom_line() + 
  labs(title = "Cumulative Deaths", 
       subtitle = "Greenville County", 
       caption = "Source:New York Times")  + 
  ylab("Cumulative Fatalities")

p4 <- cc %>% 
  filter(Combined_Key == Key) %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Date, Deaths) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Deaths)) +  
  geom_point(size = 1) +
  geom_segment(aes( x = Date, xend = Date, y = 0, yend = Deaths)) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, 13, 2)) +
  theme_bw() +
  theme(text=element_text(family=font_family1, color = font_color)) +
  geom_smooth(se = FALSE)+ 
  labs(title = "Daily Deaths", 
       subtitle = "Greenville County", 
       caption = "Source:New York Times") + 
  ylab("Daily Fatalities")


top_counties <- cc %>%  
  filter(Province_State == State_Key) %>%
  select(Date, Admin2, Difference) %>%
  group_by(Admin2) %>%  
  filter(Date == max(Date)) %>%  
  arrange(desc(Difference)) %>% 
  ungroup() %>% 
  top_n(6)


compar_high <- cc %>%  
  filter(Province_State == State_Key) %>%  
  filter(Date >= max(as.Date(Date)) - tspan) %>%
  summarize(compar_high = max(Difference)) %>%  
  pull()
  
compar_counties <- cc %>% 
  filter(Province_State == State_Key) %>%  
  filter(Date >= max(as.Date(Date)) - tspan) %>% 
  select(Date, Admin2, Difference) %>% 
  filter(Admin2 %in% top_counties$Admin2) %>% 
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Difference)) +  
  geom_point(size = .75) +
  geom_segment(aes( x = Date, xend = Date, y = 0, yend = Difference), alpha = .5) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, compar_high, 50)) + 
  facet_wrap(~Admin2, ncol = 3) +
  theme_bw() +
  theme(text=element_text(family=font_family1, color = font_color)) +
  geom_smooth(se = FALSE) + 
  labs(title = "Daily Cases by county", 
       subtitle = "Graph shows the 5 counties with the most daily cases", 
       caption = "Source:New York Times") + 
  ylab("Daily Cases")

last_update_for_county <- cc %>% 
  filter(Combined_Key == Key) %>%  
  filter(Date >= max(as.Date(Date))) %>%  
  select(Date) %>%  
  pull()
  


# load testing data
testing <- read_csv("data_world_download/3_covid_tracking_project_historical_testing_numbers_and_covid_deaths_by_state.csv", 
    col_types = cols(date = col_date(format = "%Y-%m-%d %H:%M:%S"), 
        last_update_et = col_datetime(format = "%Y-%m-%d %H:%M:%S"))) %>% filter(state == State_Key)

high_positive_tests <-  testing %>%  
  filter(date > fdate) %>%  
  summarize(max_rate = max(positivity_rate_7_day_rolling_avg)) %>% 
  pull()


p1_testing <- testing %>%  
  filter(date > fdate ) %>% 
  ggplot(aes(x = date, y = positivity_rate_7_day_rolling_avg)) + 
  geom_line() +
  scale_y_continuous(breaks=seq(0, high_positive_tests, 2)) +
  theme_bw() +
  theme(text=element_text(family=font_family1, color = font_color)) +
  labs(title = "Rate of Positive Tests \n in South Carolina", 
       subtitle = "7 Day Rolling Avg", 
       caption = "Source: Associated Press, The COVID Tracking Project") + 
  ylab("Positive Rate, 7day rolling avg.")

p2_testing <- testing %>%
  filter(date > fdate ) %>%
  select(date, cumulative_total_people_tested) %>%
  ggplot(aes(x = date, y = 	cumulative_total_people_tested)) +
  geom_line() +
  scale_y_continuous(labels = scales::comma) +
  theme_bw() +
  theme(text=element_text(family=font_family1, color = font_color)) +
  labs(title = "Cumulative number of Tests \n in South Carolina",
       caption = "Source: Associated Press, The COVID Tracking Project",
       colour = "") +
  ylab("Number of Tests")

percent_positive <- testing %>%  
  filter(date == max(date)) %>%  
  select(positivity_rate_7_day_rolling_avg) %>% 
  mutate(positivity_rate_7_day_rolling_avg = paste(positivity_rate_7_day_rolling_avg, "%", sep = "")) %>% 
  pull() 

last_update <- testing %>%  
  filter(date == max(date)) %>% 
  select(last_update_et) %>% 
  pull()
```
## Testing and percent positive for all of South Carolina  
### Most recent percent positive:`r percent_positive` at `r last_update` 
```{r sc }
library(patchwork)
p1_testing + p2_testing
```

###  Data for `r Key` and surrounding counties. Data updated: `r last_update_for_county`  

```{r county compr, fig.width=7}


compar_counties

```
\newpage

## County Daily Summary for Greenville County SC  

`r subtitle`  
```{r summary table}

cc %>%  
  filter(Combined_Key == Key) %>% 
  filter(Date == max(Date)) %>%  
  select(Cases, Difference, Deaths, Cumulative_Deaths) %>% 
  rename(`Cumulative` = Cases, `New Daily` = Difference)  %>%  
  mutate_if(is.numeric, scales::comma) %>% 
  pander()

View(
cc %>%  
  filter(Combined_Key == Key) %>% 
  filter(Date >= max(Date)- 14) %>%  
  select(Date, Cases, Difference, Deaths, Cumulative_Deaths) %>% 
  arrange(desc(Date))
)
```


```{r run charts }

p1 + p2

p3 + p4


```


```{r cumulative cases, fig.align = "center", fig.width = 8, fig.height=25, echo = FALSE, message=FALSE, warning=FALSE}
khh_download <- "5/7/2020"

loadfonts(device = "win")

pop_lookup <- read_rds(here::here("population_lookup.rds"))

cc <- read_csv("data_world_download/COVID-19 Activity.csv",
                col_types = cols(REPORT_DATE = col_date(format = "%Y-%m-%d"),
                                 COUNTY_NAME = col_character(), COUNTY_FIPS_NUMBER = col_character(),
                                 PEOPLE_POSITIVE_CASES_COUNT = col_number(),
                                 PEOPLE_POSITIVE_NEW_CASES_COUNT = col_number(),
                                 PEOPLE_DEATH_COUNT = col_number(),
                                 PEOPLE_DEATH_NEW_COUNT = col_number()))   %>% 
  select(Date = REPORT_DATE,
         Admin2 = COUNTY_NAME,
         Province_State = PROVINCE_STATE_NAME,
         Country_Region = COUNTRY_SHORT_NAME,
         country_code = COUNTRY_ALPHA_2_CODE,
         CONTINENT_NAME,
         Cases = PEOPLE_POSITIVE_CASES_COUNT,
         Difference = PEOPLE_POSITIVE_NEW_CASES_COUNT,
         Deaths = PEOPLE_DEATH_NEW_COUNT,
         Cumulative_Deaths = PEOPLE_DEATH_COUNT,
  ) %>%
  mutate(Combined_Key = paste(Admin2, Province_State, country_code, sep = ", ")) %>%  
  left_join(pop_lookup, by = "Combined_Key") 

  

#governors
gov <- read_csv(here::here("kh_sets", "governors.csv")) %>%  
  select(state_name, state_code, party, name, gender, religion, date_of_birth, entered_office)

#set parameters
date_of_data <- format(max(cc$Date, "%d-%b-%Y"))
caption1 <- paste("Data updated on ", date_of_data, sep = "") 


#corona policy
policy <- read_csv(here::here("kh_sets", "khn_policy.csv")) %>%  
  filter(Location != "United States") %>%  
  filter(Location != "District of Columbia") %>%  
  filter(!is.na(`Stay at Home Order`))%>%  
  select(-Footnotes)






ma_days <- 7
subtite1 <- paste("Moving average over ", ma_days, " days", sep = "")

#crunch data
df1 <-  cc %>%  
  filter(Date > "2020-03-01") %>% 
  select(Province_State, Date, Population_Count, everything()) %>% 
  group_by(Province_State, Date) %>% 
  summarize_if(is.numeric, sum, na.rm = TRUE) %>% 
  left_join(gov, by = c("Province_State" = "state_name")) %>%  
  mutate(Cases_pc = (Cases/Population_Count)*100000) %>% 
  mutate(Difference_pc = (Difference/Population_Count)*100000) %>% 
  mutate(Deaths_pc = (Deaths/Population_Count)*100000) %>% 
  mutate(Cumulative_Deaths_pc = (Cumulative_Deaths/Population_Count)*100000) %>%  
  filter(!is.na(party))

  

```










```{r states comparision, fig.align = "center", fig.width = 8, fig.height=25, echo = FALSE, message=FALSE, warning=FALSE}
factorize_ps <- df1 %>%   
  distinct(party, Province_State) %>%  
  arrange(party, Province_State) %>%  
  ungroup() %>% 
  mutate(order = c(1:50)) %>%  
  select(-party)
```


```{r geofact, fig.align = "center", fig.width = 8, fig.height=8, echo = FALSE, message=FALSE,}
library(geofacet)

map_high <-  df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  filter(Difference_pc == max(Difference_pc)) %>% 
  select(Difference_pc) %>%  
  pull()
  

df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  ggplot(aes(x = Date, y = Difference_pc)) + 
  scale_y_continuous(labels = scales::comma, breaks = seq(0, map_high, 25)) +
  geom_smooth(aes(colour = party), se = FALSE) +
  # geom_segment(aes(x = Date, y = Difference_pc, xend = Date, yend = 0, colour = party ), alpha = .5) + 
  # geom_point(aes(x = Date, y = Difference_pc,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  facet_geo(~ state_code) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text=element_text(family=font_family1)) +
  labs(title = "Daily Cases By state, adjusted for Population", 
       subtitle = "Color for Governor's Political Party",
       caption = caption1, 
       y = "Daily Cases per 100K")

df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  mutate(c_to_d_ratio = Deaths/lag(Difference, n = 30)) %>% 
  ggplot(aes(x = Date, y = c_to_d_ratio)) + 
  scale_y_continuous(labels = scales::comma, breaks = seq(0, map_high, 25)) +
  geom_smooth(aes(colour = party), se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_geo(~ state_code) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text=element_text(family=font_family1)) +
  labs(title = "Deaths to New Cases Ratio", 
       subtitle = "Color for Governor's Political Party \n (Deaths/Number of New Cases 30 days before)",
       caption = caption1, 
       y = "Daily Cases per 100K")


df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  mutate(c_to_d_ratio = Deaths/lag(Difference, n = 30)) %>% 
  ggplot(aes(x = Date, y = c_to_d_ratio, group = Province_State)) +
  geom_smooth(aes(colour = party), se = FALSE, size = .5) +
  scale_color_manual(values = c("blue", "red")) +
  labs(title = "In Development")

```

```{r test}
testing2 <- read_csv("data_world_download/3_covid_tracking_project_historical_testing_numbers_and_covid_deaths_by_state.csv", 
    col_types = cols(date = col_date(format = "%Y-%m-%d %H:%M:%S"), 
        last_update_et = col_datetime(format = "%Y-%m-%d %H:%M:%S"))) 

```

