---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", fig.width = 8, fig.height=5, echo = FALSE, message=FALSE, warning=FALSE)
```

```{r load data}
library(readr)
library(tidyverse)
library(readxl)
library(zoo)
library(ggthemes)
library(extrafont)
library(patchwork)
library(kableExtra)

khh_download <- "5/7/2020"

loadfonts(device = "win")

pop_lookup <- read_rds(here::here("population_lookup.rds"))

cc <- 
df1 <- read_csv("data_world_download/COVID-19 Activity.csv",
                col_types = cols(REPORT_DATE = col_date(format = "%Y-%m-%d"),
                                 COUNTY_NAME = col_character(), COUNTY_FIPS_NUMBER = col_character(),
                                 PEOPLE_POSITIVE_CASES_COUNT = col_number(),
                                 PEOPLE_POSITIVE_NEW_CASES_COUNT = col_number(),
                                 PEOPLE_DEATH_COUNT = col_number(),
                                 PEOPLE_DEATH_NEW_COUNT = col_number()))   %>% 
  select(Date = REPORT_DATE,
         Admin2 = COUNTY_NAME,
         Province_State = PROVINCE_STATE_NAME,
         Country_Region = COUNTRY_SHORT_NAME,
         country_code = COUNTRY_ALPHA_2_CODE,
         CONTINENT_NAME,
         Cases = PEOPLE_POSITIVE_CASES_COUNT,
         Difference = PEOPLE_POSITIVE_NEW_CASES_COUNT,
         Deaths = PEOPLE_DEATH_NEW_COUNT,
         Cumulative_Deaths = PEOPLE_DEATH_COUNT,
  ) %>%
  mutate(Combined_Key = paste(Admin2, Province_State, country_code, sep = ", ")) %>%  
  left_join(pop_lookup, by = "Combined_Key") 

  

#governors
gov <- read_csv(here::here("kh_sets", "governors.csv")) %>%  
  select(state_name, state_code, party, name, gender, religion, date_of_birth, entered_office)

#set parameters
date_of_data <- format(max(cc$Date, "%d-%b-%Y"))
caption1 <- paste("Data updated on ", date_of_data, sep = "") 



# #kh_data 
# vaccines <- read_csv(here::here("kh_sets", "khn_policy_vaccines.csv")) %>%  
#   filter(Location != "United States") %>%  
#   filter(Location != "District of Columbia") %>%  
#   filter(!is.na(`Influenza Deaths`)) %>%  
#   select(-Footnotes)
# 
# #kh_ medicad expansion
# expansion <- read_csv(here::here("kh_sets","khn_medicaidexpansion.csv") )%>%  
#   filter(Location != "United States") %>%  
#   filter(Location != "District of Columbia") %>%  
#   filter(!is.na(Employer))

#corona policy
policy <- read_csv(here::here("kh_sets", "khn_policy.csv")) %>%  
  filter(Location != "United States") %>%  
  filter(Location != "District of Columbia") %>%  
  filter(!is.na(`Stay at Home Order`))%>%  
  select(-Footnotes)

# #demographic data 
# demo <- read_csv(here::here("kh_sets", "khn_policydemo.csv")) %>%  
#   filter(Location != "United States") %>%  
#   filter(Location != "District Of Columbia") %>%  
#   filter(!is.na(`Number at risk, adults 18 and older`)) %>%  
#   select(-Footnotes)
# 
# 
# #additional corona variables
# additional <- read_csv(here::here("kh_sets", "khn_policy_additional.csv")) %>%  
#   filter(Location != "United States") %>%  
#   filter(Location != "District of Columbia") %>%  
#   filter(!is.na(`Long-term care facilities with known cases`)) %>%  
#   select(-Footnotes)
# 
# #additional long term care metrics
# longterm <- read_csv(here::here("kh_sets", "khn_policy_longtermcare.csv")) %>%  
#   filter(Location != "United States") %>%  
#   filter(Location != "District of Columbia") 





ma_days <- 7
subtite1 <- paste("Moving average over ", ma_days, " days", sep = "")

#crunch data
df1 <-  cc %>%  
  filter(Date > "2020-03-01") %>% 
  select(Province_State, Date, Population_Count, everything()) %>% 
  group_by(Province_State, Date) %>% 
  summarize_if(is.numeric, sum, na.rm = TRUE) %>% 
  left_join(gov, by = c("Province_State" = "state_name")) %>%  
  mutate(Cases_pc = (Cases/Population_Count)*100000) %>% 
  mutate(Difference_pc = (Difference/Population_Count)*100000) %>% 
  mutate(Deaths_pc = (Deaths/Population_Count)*100000) %>% 
  mutate(Cumulative_Deaths_pc = (Cumulative_Deaths/Population_Count)*100000) %>%  
  filter(!is.na(party))

  

```










```{r states comparision, fig.align = "center", fig.width = 8, fig.height=25, echo = FALSE, message=FALSE, warning=FALSE}
factorize_ps <- df1 %>%   
  distinct(party, Province_State) %>%  
  arrange(party, Province_State) %>%  
  ungroup() %>% 
  mutate(order = c(1:50)) %>%  
  select(-party)

df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  ggplot(aes(x = Date, y = Difference_pc, group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Difference_pc, xend = Date, yend = 0, colour = party ), alpha = .5) + 
  geom_point(aes(x = Date, y = Difference_pc,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(~Province_State, ncol = 6) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(title = "The States on thier own", 
       subtitle = "adjusted for population",
       caption = caption1)


df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  ggplot(aes(x = Date, y = Difference , group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Difference , xend = Date, yend = 0, colour = party ), alpha = .5) + 
  geom_point(aes(x = Date, y = Difference ,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(~Province_State, ncol = 6) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(title = "The States on thier own", 
       subtitle = "NOT adjusted for population",
       caption = caption1)
df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  ggplot(aes(x = Date, y = Difference_pc, group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Difference_pc, xend = Date, yend = 0, colour = party ), alpha = .5) + 
  geom_point(aes(x = Date, y = Difference_pc,colour = party )) + 
  scale_y_continuous(trans='log2') +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(~Province_State, ncol = 6) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(title = "The States on thier own - Log Scale", 
       subtitle = "adjusted for population",
       caption = caption1)


df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  ggplot(aes(x = Date, y = Difference , group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Difference , xend = Date, yend = 0, colour = party ), alpha = .5) + 
  geom_point(aes(x = Date, y = Difference ,colour = party )) + 
  scale_y_continuous(trans='log2') +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(~Province_State, ncol = 6) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(title = "The States on thier own", 
       subtitle = "NOT adjusted for population",
       caption = caption1)
```


```{r geofact, fig.align = "center", fig.width = 8, fig.height=8, echo = FALSE, message=FALSE,}
library(geofacet)
df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  ggplot(aes(x = Date, y = Difference_pc))  +
  geom_smooth(aes(colour = party), se = FALSE) +
  # geom_segment(aes(x = Date, y = Difference_pc, xend = Date, yend = 0, colour = party ), alpha = .5) + 
  # geom_point(aes(x = Date, y = Difference_pc,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  facet_geo(~ state_code) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(title = "The States on thier own", 
       subtitle = "adjusted for population",
       caption = caption1)
```

```{r cumulative cases, fig.align = "center", fig.width = 8, fig.height=25, echo = FALSE, message=FALSE, warning=FALSE}
df1 %>% 
  ungroup() %>% 
  left_join(factorize_ps, by = "Province_State") %>%  
  mutate(Province_State = as.factor(Province_State)) %>%  
  mutate(Province_State = fct_reorder(Province_State, order)) %>% 
  ggplot(aes(x = Date, y = Cases_pc , group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Cases_pc , xend = Date, yend = 0, colour = party ), alpha = .5) + 
  geom_point(aes(x = Date, y = Cases_pc ,colour = party )) + 
  scale_y_continuous(trans='log2') +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(~Province_State, ncol = 6) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  labs(title = "The States on thier own - Cumulative Cases  - Log Scale", 
       subtitle = "Adjusted for population",
       caption = caption1)
```

```{r moving average plots}
#moving average of cases by party = unadjusted for population
df1 %>% 
  ggplot(aes(x = Date, y = Difference))  +
  geom_line(aes(colour = party , group = Province_State), alpha = .25) + 
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Daily cases by party", 
       subtitle = "",
       caption = "")




#moving average of cases by party = adjusted for population
df1 %>% 
  group_by(party, Province_State, Date) %>%  
  ggplot(aes(x = Date, y = Difference_pc))  +
  geom_line(aes(colour = party, group = Province_State), alpha = .25) +
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Daily cases by party adjusted by populaton", 
       subtitle = "Daily Cases per 100,000 population",
       caption = "")


#moving average of cases by party = unadjusted for population new york removed
df1 %>% 
  filter(Province_State != "New York") %>% 
  ggplot(aes(x = Date, y = Difference))  +
  geom_line(aes(colour = party , group = Province_State), alpha = .25) + 
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Daily cases by party", 
       subtitle = "New York State removed",
       caption = "")

#moving average of cases by party = adjusted for population new york removed
df1 %>% 
  filter(Province_State != "New York") %>% 
  ggplot(aes(x = Date, y = Difference_pc))  +
  geom_line(aes(colour = party, group = Province_State), alpha = .25) +
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Daily cases by party adjusted by populaton", 
       subtitle = "New York State removed \n Daily Cases per 100,000 population",
       caption = "")

#agragated by party and adjusted for by population
df1 %>% 
  group_by(party, Date) %>% 
  summarize(Difference_pc = sum(Difference_pc)) %>% 
  ggplot(aes(x = Date, y = Difference_pc, group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Difference_pc, xend = Date, yend = 0, colour = party )) + 
  geom_point(aes(x = Date, y = Difference_pc,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Who makes the turn", 
       subtitle = "",
       caption = "")

#agragated by party and adjusted for by population take new york out
df1 %>% 
  filter(Province_State != "New York") %>% 
  group_by(party, Date) %>% 
  summarize(Difference_pc = sum(Difference_pc)) %>% 
  ggplot(aes(x = Date, y = Difference_pc, group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Difference_pc, xend = Date, yend = 0, colour = party )) + 
  geom_point(aes(x = Date, y = Difference_pc,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Who makes the turn (without New York)", 
       subtitle = "",
       caption = "")


#### --- cumulative deaths
#cum deaths of cases by party = unadjusted for population
df1 %>% 
  ggplot(aes(x = Date, y = Cumulative_Deaths))  +
  geom_line(aes(colour = party , group = Province_State), alpha = .25) + 
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Cumulative Fatalities, by party", 
       subtitle = "",
       caption = "")

#cum deaths by party = adjusted for population
df1 %>% 
  ggplot(aes(x = Date, y = Cumulative_Deaths_pc))  +
  geom_line(aes(colour = party, group = Province_State), alpha = .25) +
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Cumulative Fatalities, by party adjusted by populaton", 
       subtitle = "Daily Cases per 100,000 population",
       caption = "")


#cum deaths by party = unadjusted for population new york removed
df1 %>% 
  filter(Province_State != "New York") %>% 
  ggplot(aes(x = Date, y = Cumulative_Deaths))  +
  geom_line(aes(colour = party , group = Province_State), alpha = .25) + 
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Cumulative Fatalities, by party", 
       subtitle = "New York State removed",
       caption = "")

#cum deaths by party = adjusted for population new york removed
df1 %>% 
  filter(Province_State != "New York") %>% 
  ggplot(aes(x = Date, y = Cumulative_Deaths_pc))  +
  geom_line(aes(colour = party, group = Province_State), alpha = .25) +
  geom_smooth(color = "black", se = FALSE) +
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap( ~ party) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Cumulative Fatalities, by party adjusted by populaton", 
       subtitle = "New York State removed \n Daily Cases per 100,000 population",
       caption = "")

#agragated by party and adjusted for by population
df1 %>% 
  group_by(party, Date) %>% 
  summarize(Cumulative_Deaths_pc = sum(Cumulative_Deaths_pc)) %>% 
  ggplot(aes(x = Date, y = Cumulative_Deaths_pc, group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Cumulative_Deaths_pc, xend = Date, yend = 0, colour = party )) + 
  geom_point(aes(x = Date, y = Cumulative_Deaths_pc,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  theme_classic() +
  # theme(legend.position = "none") + 
  labs(title = "Cumulative Fatalities, aggragated by population that votes in a party", 
       subtitle = "",
       caption = "")


```



```{r easing }
caption1 <- paste("Kaiser health data updated ", khh_download, sep = "")


df1 %>% 
  left_join(policy %>% select(Location, easing  = `State Is Easing Social Distancing Measures`), by = c("Province_State" = "Location")) %>% 
  group_by(easing, party, Date) %>% 
  summarize(Difference_pc = sum(Difference_pc)) %>% 
  ggplot(aes(x = Date, y = Difference_pc, group = party))  +
  geom_smooth(color = "black", se = FALSE) +
  geom_segment(aes(x = Date, y = Difference_pc, xend = Date, yend = 0, colour = party ), alpha = .5) + 
  geom_point(aes(x = Date, y = Difference_pc,colour = party )) + 
  scale_color_manual(values = c("blue", "red")) +
  facet_wrap(~easing) +
  theme_classic() +
  theme(legend.position = "none") + 
  labs(title = "Easing Social Distancing Measures", 
       subtitle = "adjusted for population",
       caption = caption1)
```
