---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", fig.width = 8, fig.height=5, echo = FALSE, message=FALSE, warning=FALSE)
```

```{r run code}
library(readr)
library(tidyverse)
library(readxl)
library(zoo)
library(ggthemes)
library(extrafont)
library(kableExtra)
library(sf)


loadfonts(device = "win")

#load data set downloaded from Data world
cc <- read_csv("data_world_download/COVID-19 Activity.csv",
col_types = cols(REPORT_DATE = col_date(format = "%Y-%m-%d"),
COUNTY_NAME = col_character(), COUNTY_FIPS_NUMBER = col_character(),
PEOPLE_POSITIVE_CASES_COUNT = col_number(),
PEOPLE_POSITIVE_NEW_CASES_COUNT = col_number(),
PEOPLE_DEATH_COUNT = col_number(),
PEOPLE_DEATH_NEW_COUNT = col_number()))   %>% 
  select(Date = REPORT_DATE,
         Admin2 = COUNTY_NAME,
         Province_State = PROVINCE_STATE_NAME,
         Country_Region = COUNTRY_SHORT_NAME,
         country_code = COUNTRY_ALPHA_2_CODE,
         CONTINENT_NAME,
         Cases = PEOPLE_POSITIVE_CASES_COUNT,
         Difference = PEOPLE_POSITIVE_NEW_CASES_COUNT,
         Deaths = PEOPLE_DEATH_NEW_COUNT,
         Cumulative_Deaths = PEOPLE_DEATH_COUNT,
         )



date_of_data <-  max(cc$Date) 
date_of_data <- format(date_of_data, "%d%B%Y")
subtitle <- paste("Data updated on ", date_of_data, sep = "") 
tspan <- 60

Key <- us_states$Province_State[i]


# Key <-  "South Carolina"


#create map

#load city lat long


map_data <- cc%>%  
  filter(Province_State == Key) %>%  
  distinct(Province_State)

st_n <- map_data %>% mutate(Province_State = str_to_lower(Province_State)) %>% pull(1) 

all_states <- map_data("state")


state1 <- subset(all_states, region == st_n)



map_for_report <- ggplot(data = state1) +
  geom_polygon(aes(x = long, y = lat, group = group), fill = "palegreen", color = "black") +
  coord_fixed(1.3) +
  theme_void()



#crunch data for report
table1 <- cc %>% 
  filter(Province_State == Key) %>% 
  filter(Date >= max(as.Date(Date)) - tspan)  %>%  
  select(Date, Cases, Difference, Deaths, Cumulative_Deaths) %>%
  group_by(Date) %>%  
  summarize_if(is.numeric, sum) %>% 
  mutate(Date = as.Date(Date)) %>% arrange(desc(Date)) %>%  
  mutate(percentage_change = (Cases - lead(Cases))/lead(Cases)) %>% 
  mutate(daily_new_cases_difference = 
           Difference - lead(Difference)) %>%  
  filter(!is.na(percentage_change))

p_change <- table1 %>%  
  ggplot(aes(x = Date, y = percentage_change)) +  
  geom_line() + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme_classic()

p_new_cases_difference <- table1 %>%  
  ggplot(aes(x = Date, y = daily_new_cases_difference)) +  
  geom_point(aes(x = Date, y = daily_new_cases_difference)) + 
  geom_segment(aes(x = Date, xend = Date, y = 0, yend = daily_new_cases_difference)) +
  geom_smooth() +
  theme_classic()

p1 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Date, Cases, Difference) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Cases)) +  
  geom_line() + 
  theme_classic() +
  labs(title = "Cumulative Cases")

p2 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  select(Date, Cases, Difference) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Difference)) +  
  geom_point() +
  geom_segment(aes( x = Date, xend = Date, y = 0, yend = Difference)) +
  theme_classic() +
  geom_smooth(se = FALSE)+ 
  labs(title = "Daily Cases")

p3 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Cumulative_Deaths)) +  
  theme_classic() +
  geom_line() + 
  labs(title = "Cumulative Deaths")

p4 <- table1 %>% 
  filter(Date >= max(as.Date(Date)) - tspan) %>%  
  mutate(Date = as.Date(Date)) %>%  
  ggplot(aes(x = Date, y = Deaths)) +  
  geom_point() +
  geom_segment(aes( x = Date, xend = Date, y = 0, yend = Deaths)) +  theme_classic() +
  geom_smooth(se = FALSE)+ 
  labs(title = "Daily Deaths")



```
### `r Key` 
### `r subtitle`
```{r map, fig.align = "left", fig.width = 2, fig.height=2,}
map_for_report
```




 
```{r run charts}


library(patchwork)
p1 + p2

p3 + p4


p_change + p_new_cases_difference
```


